# Generic settings
ieee80211n=1
wmm_enabled=1
#country_code=FI

# Open AP
ssid=zephyr-open
channel=1

# WPA2 AP
bss=wlan2
ssid=zephyr-wpa2
channel=6
auth_algs=1
wpa=2
wpa_key_mgmt=WPA-PSK
rsn_pairwise=CCMP
wpa_passphrase=password

# WPA3 AP
#bss=wlan3
#ssid=zephyr-wpa
#channel=13
#auth_algs=1
#wpa_key_mgmt=WPA-PSK
#rsn_pairwise=CCMP
#wpa_passphrase=password
